# -*- coding: utf-8 -*-
"""General-case solver v5.7: fixed-base bending schemes + rigid-wall equilibrium.

New concept requested for v5.7:
    * The old iterative general-case solver is replaced completely.
    * n fixed-base bending schemes are generated by scaling all vertical loadings
      (soil unit weights, surcharge q and water unit weight) from 0 to 100%.
    * Each scheme provides an initial bending deflection Δx_b(z). The subsequent
      solve treats the wall as rigid, starting from that already-bent shape:
          Δx_total(z) = Δx_b(z) + Δx_rigid(z)
    * For every bending scheme, θ and z_pivot are searched; Δx_translation is
      locked kinematically by the relation tan(θ) = Δx_translation/(H_R-z_pivot).
      This reduces the rigid optimization to two independent unknowns.
    * The external work is signed. Absolute work is retained only as a diagnostic.
"""
from __future__ import annotations

from .common import *
from .reinforcement import apply_reinforcement_to_pressure_data, admissible_pivot_range
from .fixed_base_closed_form import solve_fixed_base_only_bending
import copy
import math
import os
import concurrent.futures


def _trapz(z: list[float], y: list[float]) -> float:
    if len(z) < 2:
        return 0.0
    s = 0.0
    for i in range(1, len(z)):
        dz = float(z[i]) - float(z[i - 1])
        s += 0.5 * (float(y[i - 1]) + float(y[i])) * dz
    return float(s)


def _linspace(a: float, b: float, n: int) -> list[float]:
    n = max(1, int(n))
    a = float(a); b = float(b)
    if n == 1 or abs(b - a) <= 1.0e-15:
        return [0.5 * (a + b)]
    return [a + (b - a) * i / (n - 1) for i in range(n)]


def _clip(v: float, lo: float, hi: float) -> float:
    return max(float(lo), min(float(hi), float(v)))


def _interp_profile(z_src: list[float], v_src: list[float], z_dst: list[float]) -> list[float]:
    if not z_src or not v_src:
        return [0.0 for _ in z_dst]
    out = []
    j = 0
    for zd in z_dst:
        zd = float(zd)
        while j + 1 < len(z_src) and float(z_src[j + 1]) < zd:
            j += 1
        if zd <= float(z_src[0]):
            out.append(float(v_src[0])); continue
        if zd >= float(z_src[-1]):
            out.append(float(v_src[-1])); continue
        z0 = float(z_src[j]); z1 = float(z_src[j + 1])
        v0 = float(v_src[j]); v1 = float(v_src[j + 1])
        t = 0.0 if abs(z1 - z0) < 1e-30 else (zd - z0) / (z1 - z0)
        out.append(v0 + t * (v1 - v0))
    return out


def _scaled_load_model(model: ModelInput, factor: float) -> ModelInput:
    """Return a copy with all loadings scaled by factor.

    The requested reduction is applied consistently to γ, γ_sat, surcharge q and
    γ_w. Geometry, strength, stiffness, water levels and seismic coefficients are
    not scaled.
    """
    f = _clip(float(factor), 0.0, 1.0)
    m = copy.deepcopy(model)
    m.left.q = float(m.left.q) * f
    m.right.q = float(m.right.q) * f
    m.gamma_w = float(m.gamma_w) * f
    for layer in list(m.left_layers) + list(m.right_layers):
        layer.gamma = float(layer.gamma) * f
        layer.gamma_sat = float(layer.gamma_sat) * f
    return m


def _bending_schemes(model: ModelInput, z: list[float], n_schemes: int) -> list[dict]:
    n_schemes = max(2, int(n_schemes))
    out = []
    for i, f in enumerate(_linspace(0.0, 1.0, n_schemes), start=1):
        if f <= 1.0e-15:
            wb = [0.0 for _ in z]
            out.append({
                "scheme": i,
                "load_factor": 0.0,
                "bending_deflection": wb,
                "bending_status": "zero-load: no fixed-base solve",
                "bending_iterations": 0,
                "bending_max_abs_m": 0.0,
            })
            continue
        fm = _scaled_load_model(model, f)
        fm.solver_mode = "fixed_base_only_bending"
        # Keep the user's profile grid; this makes scheme profiles directly comparable.
        fixed = solve_fixed_base_only_bending(fm)
        wb = _interp_profile(fixed.z, fixed.deflection, z)
        out.append({
            "scheme": i,
            "load_factor": float(f),
            "bending_deflection": wb,
            "bending_status": str(fixed.status),
            "bending_iterations": int((fixed.summary or {}).get("iterations", 0)),
            "bending_max_abs_m": max(abs(v) for v in wb) if wb else 0.0,
        })
    return out


def _dx_from_theta_zp(theta_deg: float, z_pivot: float, H: float) -> float:
    """Kinematic lock: tan(theta) = dx_translation / (H_R - z_pivot)."""
    lever = max(float(H) - float(z_pivot), 0.0)
    return float(lever * math.tan(math.radians(float(theta_deg))))


def _rigid_component_locked(z: list[float], theta_deg: float, z_pivot: float, H: float) -> tuple[list[float], float]:
    dx = _dx_from_theta_zp(theta_deg, z_pivot, H)
    t = math.tan(math.radians(float(theta_deg)))
    zp = float(z_pivot)
    return [dx + t * (zp - float(zi)) for zi in z], dx


def _rigid_component_free(z: list[float], dx: float, theta_deg: float, z_pivot: float) -> list[float]:
    """Rigid translation/rotation component used after the imposed bending shape.

    This is intentionally the same kinematic form as the no-bending solver:
        w_rigid(z) = dx_trans + tan(theta) * (z_pivot - z)

    The general-case solver must not jump to the no-bending solver in the
    EI->infinity limit.  Instead, every general-case candidate is evaluated by
    adding this rigid component to the current bending shape and by calling the
    same analytical pressure engine on the resulting total displacement field.
    When the bending shape is negligible, this search space naturally becomes
    the rigid/no-bending search space.
    """
    t = math.tan(math.radians(float(theta_deg)))
    zp = float(z_pivot)
    return [float(dx) + t * (zp - float(zi)) for zi in z]


def _bending_strain_energy(z: list[float], w: list[float], EI: float) -> float:
    """Beam strain energy per metre length: U = 1/2 ∫ EI κ² dz.

    The fixed-base bending shape is already in metres. Curvature is estimated
    by finite differences on the solver grid. This is used as an energy
    diagnostic/selection criterion for the general case, not as a replacement
    for force and moment equilibrium.
    """
    if len(z) < 3 or len(w) < 3:
        return 0.0
    curv = [0.0 for _ in z]
    for i in range(1, len(z) - 1):
        dz1 = float(z[i]) - float(z[i - 1])
        dz2 = float(z[i + 1]) - float(z[i])
        if abs(dz1) < 1e-30 or abs(dz2) < 1e-30:
            continue
        s1 = (float(w[i]) - float(w[i - 1])) / dz1
        s2 = (float(w[i + 1]) - float(w[i])) / dz2
        curv[i] = 2.0 * (s2 - s1) / (dz1 + dz2)
    curv[0] = curv[1]
    curv[-1] = curv[-2]
    return 0.5 * float(EI) * _trapz(z, [c * c for c in curv])


def _force_moment_work(z: list[float], q: list[float], p_left: list[float], p_right: list[float], w_total: list[float], w_bending: list[float], w_rigid: list[float], z_pivot: float, EI: float = 0.0) -> dict[str, float]:
    """Force, moment and transparent energy bookkeeping.

    Sign convention used throughout the code:
        q_net = p_right - p_left
        W_right = ∫ p_right(z) w(z) dz
        W_left  = -∫ p_left(z) w(z) dz   (signed contribution)
        W_net   = W_right + W_left = ∫ q_net(z) w(z) dz

    The wall bending strain energy is computed only from the flexible bending
    part. Rigid translation/rotation adds no strain energy. For transparency,
    the total mechanism work is kept separate from the bending-compatible work:
        W_total    = W_net,total = ∫q_net(w_bending+w_rigid)dz
        W_bend,net = ∫q_net w_bending dz
        W_rigid,net= ∫q_net w_rigid dz
    Only W_bend,net is compared with U_bend in the bending-energy residual.
    """
    F = _trapz(z, q)
    arms = [float(z_pivot) - float(zi) for zi in z]
    M = _trapz(z, [float(qi) * ai for qi, ai in zip(q, arms)])
    Fscale = max(_trapz(z, [abs(float(qi)) for qi in q]), 1.0)
    Mscale = max(_trapz(z, [abs(float(qi) * ai) for qi, ai in zip(q, arms)]), Fscale * max(float(z[-1] - z[0]), 1.0) * 0.05, 1.0)

    # Signed side contributions to the net external work.  The raw pressure
    # magnitudes p_left and p_right are positive, but their mechanical
    # contributions have opposite signs because q_net = p_right - p_left.
    # Therefore W_left_signed is reported as the contribution of the left side
    # to W_net, not merely the positive integral of p_left*w.
    WL_int = _trapz(z, [float(pi) * float(wi) for pi, wi in zip(p_left, w_total)])
    WR_int = _trapz(z, [float(pi) * float(wi) for pi, wi in zip(p_right, w_total)])
    WL = -WL_int
    WR = WR_int
    Wnet = WR + WL

    WL_b_int = _trapz(z, [float(pi) * float(wi) for pi, wi in zip(p_left, w_bending)])
    WR_b_int = _trapz(z, [float(pi) * float(wi) for pi, wi in zip(p_right, w_bending)])
    WL_r_int = _trapz(z, [float(pi) * float(wi) for pi, wi in zip(p_left, w_rigid)])
    WR_r_int = _trapz(z, [float(pi) * float(wi) for pi, wi in zip(p_right, w_rigid)])
    WL_b = -WL_b_int
    WR_b = WR_b_int
    WL_r = -WL_r_int
    WR_r = WR_r_int
    Wb = WR_b + WL_b
    Wr = WR_r + WL_r

    U = _bending_strain_energy(z, w_bending, EI) if float(EI) > 0.0 else 0.0
    # Energy compatibility for the wall strain energy is checked against the
    # bending component of the external work. Rigid-body motion has no bending
    # strain energy and is controlled by force/moment equilibrium; its net work
    # is reported separately as a variational diagnostic.
    Eres = Wb - U
    Eres_total = Wnet - U
    Escale = max(abs(Wb), abs(U), abs(WR_b) + abs(WL_b), 1.0e-12)
    Wabs_net = _trapz(z, [abs(float(qi) * float(wi)) for qi, wi in zip(q, w_total)])
    Wabs_sides = _trapz(z, [(abs(float(pr) * float(wi)) + abs(float(pl) * float(wi))) for pr, pl, wi in zip(p_right, p_left, w_total)])
    Fn = abs(F) / max(Fscale, 1.0e-30)
    Mn = abs(M) / max(Mscale, 1.0e-30)
    return {
        "F": F, "M": M, "Fscale": Fscale, "Mscale": Mscale,
        "F_norm": Fn, "M_norm": Mn, "score": Fn * Fn + Mn * Mn,
        "work_left_signed": WL, "work_right_signed": WR,
        "work_left_positive_integral": WL_int, "work_right_positive_integral": WR_int,
        "work_net_signed": Wnet, "work_sides_abs": Wabs_sides,
        "work_left_bending_signed": WL_b, "work_right_bending_signed": WR_b,
        "work_left_rigid_signed": WL_r, "work_right_rigid_signed": WR_r,
        "work_bending_signed": Wb, "work_rigid_signed": Wr,
        "strain_energy_bending": U,
        "energy_balance_residual": Eres,
        "energy_balance_norm": abs(Eres) / Escale,
        "total_energy_balance_residual": Eres_total,
        "rigid_work_residual": Wr,
        "work_total_signed": Wnet, "work_total_abs": Wabs_net,
        "action_work_abs": Wabs_sides,
    }


def _evaluate_locked_candidate(model: ModelInput, engine, z: list[float], w_bending: list[float], theta_deg: float, z_pivot: float) -> dict:
    w_rigid, dx = _rigid_component_locked(z, theta_deg, z_pivot, float(model.geometry.H_R))
    w_total = [float(a) + float(b) for a, b in zip(w_bending, w_rigid)]
    data = _calculate_pressures_for_deflection(model, z, w_total, engine)
    data = apply_reinforcement_to_pressure_data(data, z, w_total, model.reinforcement_supports)
    fmw = _force_moment_work(z, data["net_pressure"], data["p_left"], data["p_right"], w_total, w_bending, w_rigid, z_pivot, model.wall.effective_EI())
    return {
        "theta_deg": float(theta_deg), "z_pivot": float(z_pivot), "dx": float(dx),
        "w": w_total, "w_bending": list(w_bending), "w_rigid": w_rigid, "data": data,
        "bending_max_abs_m": max(abs(float(v)) for v in w_bending) if w_bending else 0.0,
        "work_index": float(fmw.get("work_total_abs", 0.0)),
        **fmw,
    }


def _evaluate_free_candidate(model: ModelInput, engine, z: list[float], w_bending: list[float], dx: float, theta_deg: float, z_pivot: float) -> dict:
    w_rigid = _rigid_component_free(z, dx, theta_deg, z_pivot)
    w_total = [float(a) + float(b) for a, b in zip(w_bending, w_rigid)]
    # Single authoritative pressure path: the analytical CUT engine receives
    # the total displacement field every time.  No precomputed/cached mobilized
    # pressures and no empirical K interpolation are used here.
    data = _calculate_pressures_for_deflection(model, z, w_total, engine)
    data = apply_reinforcement_to_pressure_data(data, z, w_total, model.reinforcement_supports)
    fmw = _force_moment_work(z, data["net_pressure"], data["p_left"], data["p_right"], w_total, w_bending, w_rigid, z_pivot, model.wall.effective_EI())
    return {
        "theta_deg": float(theta_deg), "z_pivot": float(z_pivot), "dx": float(dx),
        "w": w_total, "w_bending": list(w_bending), "w_rigid": w_rigid, "data": data,
        "bending_max_abs_m": max(abs(float(v)) for v in w_bending) if w_bending else 0.0,
        "work_index": float(fmw.get("work_total_abs", 0.0)),
        **fmw,
    }


def _select_candidate(candidates: list[dict], controls: SolverControls) -> tuple[dict, dict]:
    if not candidates:
        raise RuntimeError("No general-case candidates were evaluated.")

    # If the scheme has exactly zero bending, the general candidate family is
    # physically identical to the no-bending rigid family.  Use the same
    # transparent rigid selection hierarchy, but still inside the general solver
    # and with candidates evaluated by _evaluate_free_candidate.
    if max(float(r.get("bending_max_abs_m", 0.0)) for r in candidates) <= 1.0e-14:
        tol_F_r = max(0.0, float(getattr(controls, "equilibrium_force_tol", 0.01)))
        tol_M_r = max(0.0, float(getattr(controls, "equilibrium_moment_tol", 0.01)))
        tol_W_r = max(0.0, float(getattr(controls, "work_band_tol", 0.05)))
        def score_r(r): return float(r.get("score", 1.0e99))
        def work_r(r): return float(r.get("work_index", r.get("work_total_abs", 1.0e99)))
        def theta_abs_r(r): return abs(float(r.get("theta_deg", 0.0)))
        def dx_abs_r(r): return abs(float(r.get("dx", 0.0)))
        def F_ratio_r(r): return abs(float(r.get("F", 0.0))) / max(float(r.get("Fscale", 1.0)), 1.0e-30)
        def M_ratio_r(r): return abs(float(r.get("M", 0.0))) / max(float(r.get("Mscale", 1.0)), 1.0e-30)
        best_score_r = min(score_r(r) for r in candidates)
        explicit_band = [r for r in candidates if F_ratio_r(r) <= tol_F_r and M_ratio_r(r) <= tol_M_r]
        used_fallback_r = False
        if explicit_band:
            equilibrium_band = explicit_band
            score_limit_r = max(score_r(r) for r in equilibrium_band)
        else:
            used_fallback_r = True
            score_limit_r = max(best_score_r * 1.02, best_score_r + 1.0e-10)
            equilibrium_band = [r for r in candidates if score_r(r) <= score_limit_r] or [min(candidates, key=score_r)]
        min_work_r = min(work_r(r) for r in equilibrium_band)
        work_limit_r = max(min_work_r * (1.0 + tol_W_r), min_work_r + 1.0e-12)
        work_band = [r for r in equilibrium_band if work_r(r) <= work_limit_r] or equilibrium_band
        Href = max(float(max((r.get("z_pivot", 0.0) for r in candidates), default=1.0)), 1.0)
        selected_r = min(work_band, key=lambda r: (theta_abs_r(r), dx_abs_r(r), abs(float(r.get("z_pivot", 0.0)) - 0.5 * Href), score_r(r), work_r(r)))
        return selected_r, {
            "explicit force+moment+energy candidates": len(explicit_band),
            "force+moment candidates before energy filter": len(explicit_band),
            "selection used fallback residual band": bool(used_fallback_r),
            "candidate pool size": len(work_band),
            "candidate pool type": "zero-bending rigid-equivalent scheme; same transparent rigid selection hierarchy",
            "selection rule": "zero-bending scheme: equilibrium band -> near-minimum work band -> min |theta| -> min |dx|, evaluated inside the general solver",
        }

    tol_F = max(0.0, float(getattr(controls, "equilibrium_force_tol", 0.01)))
    tol_M = max(0.0, float(getattr(controls, "equilibrium_moment_tol", 0.01)))
    tol_E = max(0.0, float(getattr(controls, "energy_balance_tol", 0.10)))

    def f_ok(r): return float(r.get("F_norm", 1.0e99)) <= tol_F
    def m_ok(r): return float(r.get("M_norm", 1.0e99)) <= tol_M
    def e_ok(r): return float(r.get("energy_balance_norm", 1.0e99)) <= tol_E

    explicit = [r for r in candidates if f_ok(r) and m_ok(r) and e_ok(r)]
    eq_only = [r for r in candidates if f_ok(r) and m_ok(r)]
    used_fallback = False
    pool = explicit
    pool_type = "force+moment+energy"
    if not pool:
        used_fallback = True
        if eq_only:
            pool = eq_only
            pool_type = "force+moment only; energy used as ranking penalty"
        else:
            # When no candidate satisfies the explicit tolerances, stay near the
            # best equilibrium residual and then minimize the energy mismatch.
            best_score = min(float(r["score"]) for r in candidates)
            limit = max(best_score * 1.05, best_score + 1.0e-12)
            pool = [r for r in candidates if float(r["score"]) <= limit] or [min(candidates, key=lambda r: float(r["score"]))]
            pool_type = "near-best force/moment residual band"

    # Hierarchy: admissibility/residual quality first, energy compatibility second,
    # least two-sided work third.  This prevents a least-work boundary mechanism
    # from dominating a better-balanced mechanism.
    selected = min(pool, key=lambda r: (
        float(r.get("action_work_abs", abs(float(r.get("work_total_signed", 0.0))))),
        float(r.get("energy_balance_norm", 1.0e99)),
        abs(float(r.get("theta_deg", 0.0))),
        abs(float(r.get("dx", 0.0))),
        float(r.get("F_norm", 1.0e99))**2 + float(r.get("M_norm", 1.0e99))**2,
    ))
    return selected, {
        "explicit force+moment+energy candidates": len(explicit),
        "force+moment candidates before energy filter": len(eq_only),
        "selection used fallback residual band": used_fallback,
        "candidate pool size": len(pool),
        "candidate pool type": pool_type,
        "selection rule": "force/moment/energy admissibility first; least two-sided work selects the mechanism; energy and residuals are tie-breakers",
    }




def _global_rank_key(r: dict, controls: SolverControls) -> tuple:
    """Deterministic final ranking: admissibility first, then least action.

    The zero-load rigid-limit handling is applied outside this key.
    """
    tol_F = max(0.0, float(getattr(controls, "equilibrium_force_tol", 0.01)))
    tol_M = max(0.0, float(getattr(controls, "equilibrium_moment_tol", 0.01)))
    tol_E = max(0.0, float(getattr(controls, "energy_balance_tol", 0.10)))
    Fn = float(r.get("F_norm", 1.0e99))
    Mn = float(r.get("M_norm", 1.0e99))
    En = float(r.get("energy_balance_norm", 1.0e99))
    admissible = (Fn <= tol_F and Mn <= tol_M and En <= tol_E)
    eq_only = (Fn <= tol_F and Mn <= tol_M)
    return (
        0 if admissible else (1 if eq_only else 2),
        float(r.get("action_work_abs", abs(float(r.get("work_total_signed", 0.0))))),
        En,
        abs(float(r.get("theta_deg", 0.0))),
        abs(float(r.get("dx", 0.0))),
        Fn * Fn + Mn * Mn,
        -float(r.get("load_factor", 0.0)),
    )

def _optimize_scheme(model: ModelInput, engine, z: list[float], scheme: dict) -> tuple[dict, dict]:
    H = max(float(model.geometry.H_R), 1.0e-9)
    zp_min, zp_max, zp_reason = admissible_pivot_range(model.geometry.H_L, H, model.reinforcement_supports)

    # The post-bending problem is a rigid-wall equilibrium search on the already
    # deformed shape.  Therefore dx_trans must remain an independent rigid-body
    # translation, exactly as in the no-bending solver.  This is not a fallback to
    # another model; it is the general-case kinematics evaluated normally with
    # w_total = w_bending + w_rigid and the common analytical pressure engine.
    dx_seed = max(0.0, float(getattr(model.movement, "dx_trans", 0.0)))
    theta_seed = max(0.0, abs(float(getattr(model.movement, "theta_rot_deg", 0.0))))
    seed_zp = _clip(float(model.movement.z_pivot), zp_min, zp_max)

    dx_max = max(dx_seed * 3.0, 0.02 * H, 0.05)
    dx_max = min(dx_max, 0.20 * H)
    theta_max = max(theta_seed * 3.0, 5.0)
    theta_max = min(theta_max, 20.0)
    theta_min = 0.0

    # Use the same broad rigid-body search grid as the no-bending solver for
    # the post-bending rigid movement. This is what makes the general solver
    # approach the no-bending solution by itself when w_bending -> 0.
    theta_points = 9
    zp_points = 11
    dx_points = 9
    refine_passes = 4

    max_evals = 0
    candidates: list[dict] = []
    w_bending = scheme["bending_deflection"]

    def register(dx, th, zp):
        nonlocal max_evals
        rec = _evaluate_free_candidate(
            model, engine, z, w_bending,
            _clip(dx, 0.0, dx_max), _clip(th, theta_min, theta_max), _clip(zp, zp_min, zp_max)
        )
        candidates.append(rec)
        max_evals += 1
        return rec

    def eval_grid(dx_lo, dx_hi, th_lo, th_hi, zp_lo, zp_hi, ndx, nth, nzp):
        for dx in _linspace(dx_lo, dx_hi, ndx):
            for th in _linspace(th_lo, th_hi, nth):
                for zp in _linspace(zp_lo, zp_hi, nzp):
                    register(dx, th, zp)

    # Always include the user seed, the no-translation seed, and a broad global grid.
    register(dx_seed, theta_seed, seed_zp)
    register(0.0, theta_seed, seed_zp)
    eval_grid(0.0, dx_max, theta_min, theta_max, zp_min, zp_max, dx_points, theta_points, zp_points)

    # Local refinements around the current best force/moment residual.  The best
    # residual controls the center because equilibrium is the first admissibility
    # requirement; energy/work are selection criteria after equilibrium quality.
    dx_span = 0.30 * max(dx_max, 1.0e-9)
    th_span = 0.30 * max(theta_max, 1.0e-6)
    zp_span = 0.25 * H
    for _ in range(refine_passes):
        best_now = min(candidates, key=lambda r: float(r["score"]))
        dx_c = float(best_now["dx"]); th_c = float(best_now["theta_deg"]); zp_c = float(best_now["z_pivot"])
        eval_grid(dx_c - dx_span, dx_c + dx_span, th_c - th_span, th_c + th_span, zp_c - zp_span, zp_c + zp_span, 5, 5, 5)
        dx_span *= 0.45
        th_span *= 0.45
        zp_span *= 0.45

    best, info = _select_candidate(candidates, model.controls)
    return best, {
        "optimization evaluations": max_evals,
        "rigid search mode after bending": "free dx_trans + theta + z_pivot; common analytical pressure engine called with w_total=w_bending+w_rigid",
        "dx search min (m)": 0.0,
        "dx search max (m)": dx_max,
        "dx initial grid points": dx_points,
        "theta search min (deg)": theta_min,
        "theta search max (deg)": theta_max,
        "theta initial grid points": theta_points,
        "theta refinement passes": refine_passes,
        "z_pivot search min (m)": zp_min,
        "z_pivot search max (m)": zp_max,
        "z_pivot admissibility rule": zp_reason,
        **info,
    }

def _result_from_ranked_solutions(model: ModelInput, z: list[float], ranked: list[dict], summary_extra: dict) -> SolverResult:
    best = ranked[0]
    data = best["data"]
    V, M = _integrate_shear_moment(z, data["net_pressure"])
    rotation = _gradient(best["w"], z)
    method = str(model.controls.integration_method or "Gauss")
    table = []
    for rank, r in enumerate(ranked, start=1):
        table.append({
            "rank_by_work": rank,
            "rank": rank,
            "scheme": int(r["scheme"]),
            "load_factor": float(r["load_factor"]),
            "dx_trans_m": float(r["dx"]),
            "theta_rot_deg": float(r["theta_deg"]),
            "z_pivot_m": float(r["z_pivot"]),
            "ΣF kN/m": float(r["F"]),
            "ΣM kNm/m": float(r["M"]),
            "|ΣF|/scale": float(r["F_norm"]),
            "|ΣM|/scale": float(r["M_norm"]),
            "score": float(r["score"]),
            "W_left_signed": float(r.get("work_left_signed", 0.0)),
            "W_right_signed": float(r.get("work_right_signed", 0.0)),
            "W_total_signed": float(r.get("work_total_signed", r.get("work_net_signed", 0.0))),
            "W_net_signed": float(r.get("work_net_signed", r.get("work_total_signed", 0.0))),
            "W_sides_abs": float(r.get("work_sides_abs", r.get("action_work_abs", 0.0))),
            "W_bend_net_signed": float(r["work_bending_signed"]),
            "W_bending_net_signed": float(r["work_bending_signed"]),
            "U_bending_strain": float(r.get("strain_energy_bending", 0.0)),
            "energy_balance_residual": float(r.get("energy_balance_residual", 0.0)),
            "energy_balance_norm": float(r.get("energy_balance_norm", 0.0)),
            "W_rigid_net_signed": float(r["work_rigid_signed"]),
            "W_total_signed": float(r["work_total_signed"]),
            "W_total_abs": float(r["work_total_abs"]),
            "max_bending_deflection_m": float(r.get("bending_max_abs_m", 0.0)),
            "max_total_deflection_m": max(abs(v) for v in r["w"]) if r.get("w") else 0.0,
        })
    return SolverResult(
        solver_mode="general_case",
        status="ok",
        message="General-case v5.7 completed: fixed-base bending schemes were followed by free rigid-wall equilibrium searches on the total displacement field and ranked by admissibility, bending-energy compatibility, and least two-sided work.",
        z=z,
        p_left=data["p_left"], p_right=data["p_right"],
        sigma_left_eff=data.get("sigma_left_eff", []), sigma_right_eff=data.get("sigma_right_eff", []),
        u_left=data.get("u_left", []), u_right=data.get("u_right", []),
        sigma_left_OE=data["sigma_left_OE"], sigma_left_AE=data["sigma_left_AE"], sigma_left_PE=data["sigma_left_PE"],
        sigma_right_OE=data["sigma_right_OE"], sigma_right_AE=data["sigma_right_AE"], sigma_right_PE=data["sigma_right_PE"],
        net_pressure=data["net_pressure"], shear=V, moment=M,
        deflection=best["w"], rotation=rotation,
        K_left=data["K_left"], K_right=data["K_right"],
        m_left=data["m_left"], m_right=data["m_right"],
        dxmax_left_A=data["dxmax_left_A"], dxmax_left_P=data["dxmax_left_P"],
        dxmax_right_A=data["dxmax_right_A"], dxmax_right_P=data["dxmax_right_P"],
        deflection_compare=best.get("w_bending", []),
        deflection_compare_label="initial fixed-base bending component of selected scheme",
        convergence_history=[{"iteration": float(r["scheme"]), "max_change_m": 0.0, "max_abs_deflection_m": max(abs(v) for v in r["w"])} for r in ranked],
        summary={
            "solver": "General case v5.7: n fixed-base bending schemes + free rigid-wall solve on w_total",
            "n_bending_schemes": int(summary_extra.get("n_bending_schemes", len(ranked))),
            "ranking": "admissible candidates satisfy force, moment and bending-work/strain-energy balance; ranked by admissibility first and then least two-sided work |W_L,total|+|W_R,total|",
            "energy/work sign convention": "q_net = p_right - p_left; W_R = ∫p_right w dz; W_L = -∫p_left w dz; W_total = W_R,total + W_L,total",
            "energy compatibility formula": "W_bend,net = W_R,bend + W_L,bend ≈ U_bend, with U_bend = 0.5∫EIκ²dz; W_rigid,net is a separate diagnostic and W_total = W_bend,net + W_rigid,net",
            "selected_scheme": int(best["scheme"]),
            "selected_load_factor": float(best["load_factor"]),
            "dx_trans_m": float(best["dx"]),
            "theta_rot_deg": float(best["theta_deg"]),
            "z_pivot_m": float(best["z_pivot"]),
            "rigid kinematics after bending": "w_total(z)=w_bending(z)+dx_trans+tan(theta)*(z_pivot-z); dx_trans, theta and z_pivot are searched directly; the common analytical pressure engine is called with w_total for every candidate",
            "ΣF kN/m": float(best["F"]),
            "ΣM kNm/m": float(best["M"]),
            "|ΣF|/scale": float(best["F_norm"]),
            "|ΣM|/scale": float(best["M_norm"]),
            "normalized equilibrium score": float(best["score"]),
            "W_left_signed kN·m/m": float(best.get("work_left_signed", 0.0)),
            "W_right_signed kN·m/m": float(best.get("work_right_signed", 0.0)),
            "W_total_signed kN·m/m": float(best.get("work_total_signed", best.get("work_net_signed", 0.0))),
            "W_net_signed kN·m/m": float(best.get("work_net_signed", best.get("work_total_signed", 0.0))),
            "W_sides_abs kN·m/m": float(best.get("work_sides_abs", best.get("action_work_abs", 0.0))),
            "W_bend_net_signed kN·m/m": float(best["work_bending_signed"]),
            "W_bending_net_signed kN·m/m": float(best["work_bending_signed"]),
            "U_bending_strain kN·m/m": float(best.get("strain_energy_bending", 0.0)),
            "energy_balance_residual kN·m/m": float(best.get("energy_balance_residual", 0.0)),
            "energy_balance_norm": float(best.get("energy_balance_norm", 0.0)),
            "total_energy_balance_residual kN·m/m": float(best.get("total_energy_balance_residual", 0.0)),
            "rigid_work_residual kN·m/m": float(best.get("rigid_work_residual", best.get("work_rigid_signed", 0.0))),
            "W_rigid_net_signed kN·m/m": float(best["work_rigid_signed"]),
            "W_total_abs diagnostic kN·m/m": float(best["work_total_abs"]),
            "max_deflection_abs_m": max(abs(v) for v in best["w"]) if best.get("w") else 0.0,
            "EI": model.wall.effective_EI(), "integration_method": method,
            "H_R": model.geometry.H_R, "H_L": model.geometry.H_L,
            "left layers": len(model.left_layers), "right layers": len(model.right_layers),
            "reinforcement supports active in net pressure": len(model.reinforcement_supports),
            "general_case_solutions_table": table,
            **summary_extra,
        },
    )


def _solve_general_case_scheme_worker(args):
    """Top-level worker for multiprocessing general-case scheme optimization.

    Keep this function free of GUI state and callbacks. It receives a pickleable
    model snapshot, a depth vector and one bending scheme, then returns only the
    compact numerical result for that scheme.
    """
    model, z, sc = args
    local_engine = load_cut_engine()
    best, info = _optimize_scheme(model, local_engine, z, sc)
    return {**sc, **best, "scheme_optimization": info}


def solve_general_case(model: ModelInput, progress_callback=None) -> SolverResult:
    def _progress(**kw):
        if progress_callback is not None:
            progress_callback(dict(kw))
    engine = load_cut_engine()
    H = max(float(model.geometry.H_R), 1.0e-9)
    n = max(3, int(model.controls.n_points))
    z = safe_profile_depths(H, n)
    if float(model.wall.effective_EI()) <= 0.0:
        raise ValueError("Wall EI must be positive for the general case solver.")
    n_schemes = max(2, int(getattr(model.controls, "general_case_bending_schemes", 10)))
    _progress(status="running", message="Generating fixed-base bending schemes", stage="bending", current=0, total=n_schemes, fraction=0.0)
    schemes = _bending_schemes(model, z, n_schemes)
    solved = []
    eval_total = 0
    parallel_requested = bool(getattr(model.controls, "general_case_parallel", True))
    try:
        cpu_count = os.cpu_count() or 1
    except Exception:
        cpu_count = 1
    requested_workers = int(getattr(model.controls, "general_case_max_workers", 0) or 0)
    if requested_workers <= 0:
        requested_workers = max(1, min(n_schemes, max(cpu_count - 1, 1)))
    max_workers = max(1, min(int(requested_workers), n_schemes))

    def _solve_one_scheme(sc):
        # Serial fallback helper. It uses the same top-level implementation as
        # the multiprocessing worker, but avoids pickling when parallel mode is
        # unavailable or fails.
        return _solve_general_case_scheme_worker((model, z, sc))

    if parallel_requested and max_workers > 1:
        _progress(status="running", message=f"Solving {n_schemes} bending schemes in separate processes ({max_workers} workers)", stage="parallel_rigid_search", current=0, total=n_schemes, fraction=0.0)
        completed = 0
        try:
            # ProcessPoolExecutor keeps the Tk/Matplotlib GUI thread free and
            # prevents Python-loop CPU work from starving the event loop.
            with concurrent.futures.ProcessPoolExecutor(max_workers=max_workers) as ex:
                future_map = {ex.submit(_solve_general_case_scheme_worker, (model, z, sc)): sc for sc in schemes}
                for fut in concurrent.futures.as_completed(future_map):
                    sc = future_map[fut]
                    rec = fut.result()
                    solved.append(rec)
                    eval_total += int(rec.get("scheme_optimization", {}).get("optimization evaluations", 0))
                    completed += 1
                    _progress(status="running", message=f"Completed scheme {int(sc.get('scheme', completed))}/{n_schemes}", stage="parallel_rigid_search", current=completed, total=n_schemes, fraction=completed/max(n_schemes,1))
        except Exception as exc:
            if "stopped by user" in str(exc).lower():
                raise
            _progress(status="running", message=f"Process parallel solve failed ({exc}); falling back to serial execution", stage="serial_fallback", current=0, total=n_schemes, fraction=0.0)
            solved = []
            eval_total = 0
            for idx, sc in enumerate(schemes, start=1):
                _progress(status="running", message=f"Solving bending scheme {idx}/{n_schemes} serial fallback (load factor={float(sc.get('load_factor',0.0)):.3g})", stage="rigid_search", current=idx-1, total=n_schemes, fraction=(idx-1)/max(n_schemes,1))
                rec = _solve_one_scheme(sc)
                eval_total += int(rec.get("scheme_optimization", {}).get("optimization evaluations", 0))
                solved.append(rec)
                _progress(status="running", message=f"Completed bending scheme {idx}/{n_schemes}", stage="rigid_search", current=idx, total=n_schemes, fraction=idx/max(n_schemes,1))
    else:
        for idx, sc in enumerate(schemes, start=1):
            _progress(status="running", message=f"Solving bending scheme {idx}/{n_schemes} (load factor={float(sc.get('load_factor',0.0)):.3g})", stage="rigid_search", current=idx-1, total=n_schemes, fraction=(idx-1)/max(n_schemes,1))
            rec = _solve_one_scheme(sc)
            eval_total += int(rec.get("scheme_optimization", {}).get("optimization evaluations", 0))
            solved.append(rec)
            _progress(status="running", message=f"Completed bending scheme {idx}/{n_schemes}", stage="rigid_search", current=idx, total=n_schemes, fraction=idx/max(n_schemes,1))
    ranked = sorted(solved, key=lambda r: _global_rank_key(r, model.controls))
    # The zero-load scheme is now treated as an ordinary general-case candidate.
    # It is not a fallback to the no-bending solver; it is evaluated by the same
    # free post-bending rigid search and the same analytical pressure engine as
    # every other scheme.  This lets the general model reach the rigid limit
    # naturally when the bending component is negligible.
    summary_extra = {
        "n_bending_schemes": n_schemes,
        "total optimization evaluations": eval_total,
        "scheme load factors": [float(s["load_factor"]) for s in schemes],
        "parallel scheme execution": bool(parallel_requested and max_workers > 1),
        "parallel max workers": int(max_workers),
        "parallel note": "general-case scheme optimizations are independent; parallel mode uses ProcessPoolExecutor to keep the GUI event loop responsive and falls back to serial if needed",
        "ranking note": "zero-load scheme is an ordinary general-case candidate evaluated by the same pressure engine; candidates are first filtered by force, moment and bending-energy balance, then ranked by least two-sided work",
        "per_scheme_optimization": [r.get("scheme_optimization", {}) for r in solved],
    }
    result = _result_from_ranked_solutions(model, z, ranked, summary_extra)
    _progress(status="done", message="General-case solver completed", stage="done", current=n_schemes, total=n_schemes, fraction=1.0)
    return result


def compute_work_heatmap(model: ModelInput, theta_values: list[float] | None = None, dx_values: list[float] | None = None, z_pivot_values: list[float] | None = None, n_z: int = 41) -> dict:
    """Compatibility diagnostic for GUI heatmap calls.

    The v5.7 general solver no longer searches independent dx/θ/zp grids. This
    function maps θ-zp free rigid candidates for the full-load bending scheme so the
    existing GUI heatmap tab remains usable.
    """
    engine = load_cut_engine()
    H = max(float(model.geometry.H_R), 1.0e-9)
    z = safe_profile_depths(H, max(11, int(n_z)))
    scheme = _bending_schemes(model, z, 2)[-1]
    zp_min, zp_max, _ = admissible_pivot_range(model.geometry.H_L, H, model.reinforcement_supports)
    if theta_values is None:
        theta_values = _linspace(0.0, max(abs(float(model.movement.theta_rot_deg))*2.0, 6.0), 6)
    if z_pivot_values is None:
        z_pivot_values = _linspace(zp_min, zp_max, 17)
    # dx is no longer independent; keep a single placeholder column per locked dx.
    if dx_values is None:
        dx_values = [0.0]
    mats = [] ; fnm=[] ; mnm=[] ; frm=[] ; mrm=[] ; sm=[] ; allw=[]
    best_eq=None; best_work=None; n_eval=0
    for th in theta_values:
        Wmat=[]; Fnmat=[]; Mnmat=[]; Fraw=[]; Mraw=[]; Score=[]
        for zp in z_pivot_values:
            rec = _evaluate_locked_candidate(model, engine, z, scheme["bending_deflection"], float(th), float(zp))
            n_eval += 1
            W = float(rec["work_total_signed"]); allw.append(abs(W))
            rowW=[W]; rowFn=[rec["F_norm"]]; rowMn=[rec["M_norm"]]; rowF=[rec["F"]]; rowM=[rec["M"]]; rowS=[rec["score"]]
            Wmat.append(rowW); Fnmat.append(rowFn); Mnmat.append(rowMn); Fraw.append(rowF); Mraw.append(rowM); Score.append(rowS)
            cur={"dx":rec["dx"],"theta_deg":rec["theta_deg"],"z_pivot":rec["z_pivot"],"work_index":W,"F":rec["F"],"M":rec["M"],"F_norm":rec["F_norm"],"M_norm":rec["M_norm"],"score":rec["score"]}
            if best_work is None or W < best_work.get("work_index", 1e99): best_work=dict(cur)
            if best_eq is None or rec["score"] < best_eq.get("score", 1e99): best_eq=dict(cur)
        mats.append(Wmat); fnm.append(Fnmat); mnm.append(Mnmat); frm.append(Fraw); mrm.append(Mraw); sm.append(Score)
    Wmax=max(allw or [1.0]); Wmax = Wmax if Wmax>1e-30 else 1.0
    return {"theta_values":[float(v) for v in theta_values],"dx_values":[0.0],"z_pivot_values":[float(v) for v in z_pivot_values],"work_matrices":[[[float(v)/Wmax for v in row] for row in mat] for mat in mats],"work_raw_matrices":mats,"force_norm_matrices":fnm,"moment_norm_matrices":mnm,"force_raw_matrices":frm,"moment_raw_matrices":mrm,"score_matrices":sm,"work_normalization":Wmax,"best_work":best_work or {},"best_equilibrium":best_eq or {},"n_eval":n_eval,"candidates_rejected_by_extreme_bounds":0,"admissible_bounds":{"theta_min":min(theta_values),"theta_max":max(theta_values),"z_pivot_min":zp_min,"z_pivot_max":zp_max},"n_z":len(z),"solver_family":"general_case_v5_7_free_rigid"}
